import argparse
import csv
import glob
import os
import subprocess
import sys
from collections import defaultdict
from typing import Dict, List, Optional, Tuple


def run_nsys_stats(nsys_bin: str, rep_path: str, output_prefix: str) -> str:
    cmd = [
        nsys_bin,
        "stats",
        "--report",
        "nvtx_gpu_proj_trace",
        "--timeunit=us",
        "--force-export=true",
        "--force-overwrite=true",
        "--format",
        "csv",
        "--output",
        output_prefix,
        rep_path,
    ]
    print("[run]", " ".join(cmd))
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr, file=sys.stderr)
        raise RuntimeError(f"nsys stats failed with exit code {proc.returncode}")

    # nsys report script typically generates: <prefix>_nvtx_gpu_proj_trace.csv
    candidates = sorted(glob.glob(output_prefix + "*.csv"), key=os.path.getmtime)
    if not candidates:
        raise FileNotFoundError(
            f"No CSV generated by nsys stats under prefix: {output_prefix}"
        )
    trace_csv = candidates[-1]
    print(f"[info] trace csv: {trace_csv}")
    return trace_csv


def detect_columns(header: List[str]) -> Tuple[str, str]:
    lowered = [h.strip().lower() for h in header]

    name_col = None
    for i, h in enumerate(lowered):
        if h in ("name", "range", "range name", "nvtx range"):
            name_col = header[i]
            break
    if name_col is None:
        for i, h in enumerate(lowered):
            if "name" in h:
                name_col = header[i]
                break

    dur_col = None
    for i, h in enumerate(lowered):
        if "duration" in h or h.startswith("dur") or "time" in h and "range" in h:
            dur_col = header[i]
            break

    if name_col is None or dur_col is None:
        raise RuntimeError(
            "Cannot detect name/duration columns in CSV header. "
            f"header={header}"
        )
    return name_col, dur_col


def parse_trace_csv(csv_path: str) -> Dict[str, List[float]]:
    values: Dict[str, List[float]] = defaultdict(list)
    with open(csv_path, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise RuntimeError(f"CSV has no header: {csv_path}")
        name_col, dur_col = detect_columns(reader.fieldnames)
        print(f"[info] name_col={name_col}, dur_col={dur_col}")

        for row in reader:
            name = (row.get(name_col) or "").strip()
            if not name:
                continue
            raw_dur = (row.get(dur_col) or "").strip()
            if not raw_dur:
                continue
            try:
                dur = float(raw_dur)
            except ValueError:
                continue
            values[name].append(dur)
    return values


def split_and_average_in_order(values: List[float], bucket_count: int) -> List[float]:
    """Split values into bucket_count contiguous buckets (in order), average each bucket.

    Always returns exactly bucket_count values.
    If bucket_count > len(values), empty buckets are filled by nearest sample value.
    """
    if not values:
        return []
    n = len(values)
    bucket_count = max(1, bucket_count)
    out = []
    for i in range(bucket_count):
        start = (i * n) // bucket_count
        end = ((i + 1) * n) // bucket_count
        if start < end:
            chunk = values[start:end]
            out.append(sum(chunk) / len(chunk))
        else:
            # For empty buckets (when bucket_count > n), use nearest sample.
            idx = min(start, n - 1)
            out.append(values[idx])
    return out


def strip_leading_colon(name: str) -> str:
    return name[1:] if name.startswith(":") else name


def write_combined_stats(
    values: Dict[str, List[float]],
    out_csv: str,
    d_bucket_count: int,
    d_pick_positions: List[int],
):
    rows = []
    pick_cols = [f"d_pos_{p}_us" for p in d_pick_positions]
    for raw_name, arr in values.items():
        if not arr:
            continue

        name = strip_leading_colon(raw_name)
        cnt = len(arr)

        mean_us = None
        d_values = [None] * len(d_pick_positions)

        if name.startswith("P_"):
            mean_us = sum(arr) / cnt
        elif name.startswith("D_"):
            merged = split_and_average_in_order(arr, d_bucket_count)
            for i, pos in enumerate(d_pick_positions):
                # 1-based position indexing by user definition: 32 means merged[31]
                idx = pos - 1
                if 0 <= idx < len(merged):
                    d_values[i] = merged[idx]
        else:
            continue

        rows.append((name, cnt, mean_us, *d_values))

    rows.sort(key=lambda x: x[0])
    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["op_name", "count", "mean_us", *pick_cols])
        for r in rows:
            w.writerow(r)
    print(f"[saved] {out_csv}")


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate NVTX op stats from .nsys-rep: "
            "P_* ops -> mean, D_* ops -> p25/p50/p75/p90"
        )
    )
    parser.add_argument(
        "rep_file",
        type=str,
        help="Path to .nsys-rep file",
    )
    parser.add_argument(
        "--out-dir",
        type=str,
        default="/workspace/benchmark/sglang-afd/bash-test",
        help="Output directory for generated CSVs",
    )
    parser.add_argument(
        "--nsys-bin",
        type=str,
        default="nsys",
        help="Path to nsys executable",
    )
    parser.add_argument(
        "--d-bucket-count",
        type=int,
        default=128,
        help="For D_* ops, split sequential samples into this many ordered buckets and average each bucket.",
    )
    parser.add_argument(
        "--d-pick-positions",
        type=str,
        default="32,64,128",
        help="1-based positions to pick from D bucket-averaged sequence (comma-separated), e.g. 32,64,128",
    )
    args = parser.parse_args()

    rep_file = os.path.abspath(args.rep_file)
    if not os.path.isfile(rep_file):
        raise FileNotFoundError(f"rep file not found: {rep_file}")

    os.makedirs(args.out_dir, exist_ok=True)
    trace_prefix = os.path.join(args.out_dir, "nvtx_gpu_proj_trace")

    trace_csv = run_nsys_stats(args.nsys_bin, rep_file, trace_prefix)
    values = parse_trace_csv(trace_csv)

    combined_csv = os.path.join(args.out_dir, "nvtx_PD_combined_stats.csv")
    d_pick_positions = [int(x.strip()) for x in args.d_pick_positions.split(",") if x.strip()]
    if any(p <= 0 for p in d_pick_positions):
        raise ValueError("--d-pick-positions must be positive 1-based integers.")

    # Ensure requested positions are representable in merged buckets.
    # Example: pick 255 requires at least 255 buckets.
    effective_bucket_count = max(args.d_bucket_count, max(d_pick_positions))
    if effective_bucket_count != args.d_bucket_count:
        print(
            f"[info] auto bump d_bucket_count: {args.d_bucket_count} -> "
            f"{effective_bucket_count} to satisfy d_pick_positions={d_pick_positions}"
        )

    write_combined_stats(
        values,
        combined_csv,
        d_bucket_count=effective_bucket_count,
        d_pick_positions=d_pick_positions,
    )

    p_ops = sum(1 for k in values if strip_leading_colon(k).startswith("P_"))
    d_ops = sum(1 for k in values if strip_leading_colon(k).startswith("D_"))
    print(f"[done] P_ops={p_ops}, D_ops={d_ops}")


if __name__ == "__main__":
    main()

